### PR TITLE
Support for adding policies and certificate chains and various tests and benchmarks

### PR DESCRIPTION
**Pull request by cyrill-k**
@juagargi The PR turns out to be huge (Yongzhe renamed some struct and thus many files are affected).

Should I try to split it up into smaller parts or should we merge everything and clean it up later on?

- - -
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/fpki/21)

### CODE REVIEW

**Comment by cyrill-k** [comment]
The value is implicitly read in the function where we serialize the CAEntry objects (see [structure.go](https://github.com/cyrill-k/fpki-1/blob/master/pkg/mapserver/common/structure.go#L30). the updater then stores the serialized version of the CAEntries in the tree leaves (see [cert_updater.go](https://github.com/cyrill-k/fpki-1/blob/master/pkg/mapserver/updater/certs_updater.go#L197)).

**Review by juagargi — APPROVED** [review]
True, it is used via JSON serialization.

> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/fpki/21#-:-NLfdtVi2ELlenfpcDnL:b-mo7puf)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cyrill-k)

**Review by juagargi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/fpki/21#-:-NLfe1454EyCzNcHJQVq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cyrill-k)

**Review by juagargi — CHANGES_REQUESTED** [review]
Hmm, I retract my LGTM. UTs fail. Let me fix them.

> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/fpki/21#-:-NLfeV-Z43Su_4MXEl1s:bklaojx)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cyrill-k)

**Review by juagargi — APPROVED** [review]
:lgtm: Fixed the UT and IT failures.

> Reviewed 10 of 10 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/fpki/21#-:-NLfvyAJ4DXKsG_f198e:b-hky7ww)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cyrill-k)

**Pull request merged**
